version: "3.9"

services:
  api:
    build: ./backend
    container_name: exactum_api
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    command: sh -c "./backend/wait-for-db.sh && python backend/run.py"
    depends_on:
      - db
    volumes:
      - .:/app
    user: root 

  db:
    image: postgres:15
    container_name: exactum_db
    restart: always
    environment:
      POSTGRES_DB: exactum_db
      POSTGRES_USER: exactum_admin
      POSTGRES_PASSWORD: exactum_dev_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
